export const schemaTypeArray: string[][] = [
    [
        "Action",
        "AchieveAction",
        "LoseAction"
    ],
    [
        "Action",
        "AchieveAction",
        "TieAction"
    ],
    [
        "Action",
        "AchieveAction",
        "WinAction"
    ],
    [
        "Action",
        "AchieveAction"
    ],
    [
        "Action",
        "AssessAction",
        "ChooseAction",
        "VoteAction"
    ],
    [
        "Action",
        "AssessAction",
        "ChooseAction"
    ],
    [
        "Action",
        "AssessAction",
        "IgnoreAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReactAction",
        "AgreeAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReactAction",
        "DisagreeAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReactAction",
        "DislikeAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReactAction",
        "EndorseAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReactAction",
        "LikeAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReactAction",
        "WantAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReactAction"
    ],
    [
        "Action",
        "AssessAction",
        "ReviewAction"
    ],
    [
        "Action",
        "AssessAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "DrinkAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "EatAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "InstallAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "ListenAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "ReadAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "UseAction",
        "WearAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "UseAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "ViewAction"
    ],
    [
        "Action",
        "ConsumeAction",
        "WatchAction"
    ],
    [
        "Action",
        "ConsumeAction"
    ],
    [
        "Action",
        "ControlAction",
        "ActivateAction"
    ],
    [
        "Action",
        "ControlAction",
        "DeactivateAction"
    ],
    [
        "Action",
        "ControlAction",
        "ResumeAction"
    ],
    [
        "Action",
        "ControlAction",
        "SuspendAction"
    ],
    [
        "Action",
        "ControlAction"
    ],
    [
        "Action",
        "CreateAction",
        "CookAction"
    ],
    [
        "Action",
        "CreateAction",
        "DrawAction"
    ],
    [
        "Action",
        "CreateAction",
        "FilmAction"
    ],
    [
        "Action",
        "CreateAction",
        "PaintAction"
    ],
    [
        "Action",
        "CreateAction",
        "PhotographAction"
    ],
    [
        "Action",
        "CreateAction",
        "WriteAction"
    ],
    [
        "Action",
        "CreateAction"
    ],
    [
        "Action",
        "FindAction",
        "CheckAction"
    ],
    [
        "Action",
        "FindAction",
        "DiscoverAction"
    ],
    [
        "Action",
        "FindAction",
        "TrackAction"
    ],
    [
        "Action",
        "FindAction"
    ],
    [
        "Action",
        "InteractAction",
        "BefriendAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "AskAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "CheckInAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "CheckOutAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "CommentAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "InformAction",
        "ConfirmAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "InformAction",
        "RsvpAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "InformAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "InviteAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "ReplyAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction",
        "ShareAction"
    ],
    [
        "Action",
        "InteractAction",
        "CommunicateAction"
    ],
    [
        "Action",
        "InteractAction",
        "FollowAction"
    ],
    [
        "Action",
        "InteractAction",
        "JoinAction"
    ],
    [
        "Action",
        "InteractAction",
        "LeaveAction"
    ],
    [
        "Action",
        "InteractAction",
        "MarryAction"
    ],
    [
        "Action",
        "InteractAction",
        "RegisterAction"
    ],
    [
        "Action",
        "InteractAction",
        "SubscribeAction"
    ],
    [
        "Action",
        "InteractAction",
        "UnRegisterAction"
    ],
    [
        "Action",
        "InteractAction"
    ],
    [
        "Action",
        "MoveAction",
        "ArriveAction"
    ],
    [
        "Action",
        "MoveAction",
        "DepartAction"
    ],
    [
        "Action",
        "MoveAction",
        "TravelAction"
    ],
    [
        "Action",
        "MoveAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "AllocateAction",
        "AcceptAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "AllocateAction",
        "AssignAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "AllocateAction",
        "AuthorizeAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "AllocateAction",
        "RejectAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "AllocateAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "ApplyAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "BookmarkAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "PlanAction",
        "CancelAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "PlanAction",
        "ReserveAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "PlanAction",
        "ScheduleAction"
    ],
    [
        "Action",
        "OrganizeAction",
        "PlanAction"
    ],
    [
        "Action",
        "OrganizeAction"
    ],
    [
        "Action",
        "PlayAction",
        "ExerciseAction"
    ],
    [
        "Action",
        "PlayAction",
        "PerformAction"
    ],
    [
        "Action",
        "PlayAction"
    ],
    [
        "Action",
        "SearchAction"
    ],
    [
        "Action",
        "TradeAction",
        "BuyAction"
    ],
    [
        "Action",
        "TradeAction",
        "DonateAction"
    ],
    [
        "Action",
        "TradeAction",
        "OrderAction"
    ],
    [
        "Action",
        "TradeAction",
        "PayAction"
    ],
    [
        "Action",
        "TradeAction",
        "PreOrderAction"
    ],
    [
        "Action",
        "TradeAction",
        "QuoteAction"
    ],
    [
        "Action",
        "TradeAction",
        "RentAction"
    ],
    [
        "Action",
        "TradeAction",
        "SellAction"
    ],
    [
        "Action",
        "TradeAction",
        "TipAction"
    ],
    [
        "Action",
        "TradeAction"
    ],
    [
        "Action",
        "TransferAction",
        "BorrowAction"
    ],
    [
        "Action",
        "TransferAction",
        "DownloadAction"
    ],
    [
        "Action",
        "TransferAction",
        "GiveAction"
    ],
    [
        "Action",
        "TransferAction",
        "LendAction"
    ],
    [
        "Action",
        "TransferAction",
        "ReceiveAction"
    ],
    [
        "Action",
        "TransferAction",
        "ReturnAction"
    ],
    [
        "Action",
        "TransferAction",
        "SendAction"
    ],
    [
        "Action",
        "TransferAction",
        "TakeAction"
    ],
    [
        "Action",
        "TransferAction"
    ],
    [
        "Action",
        "UpdateAction",
        "AddAction",
        "InsertAction",
        "AppendAction"
    ],
    [
        "Action",
        "UpdateAction",
        "AddAction",
        "InsertAction",
        "PrependAction"
    ],
    [
        "Action",
        "UpdateAction",
        "AddAction",
        "InsertAction"
    ],
    [
        "Action",
        "UpdateAction",
        "AddAction"
    ],
    [
        "Action",
        "UpdateAction",
        "DeleteAction"
    ],
    [
        "Action",
        "UpdateAction",
        "ReplaceAction"
    ],
    [
        "Action",
        "UpdateAction"
    ],
    [
        "Action"
    ],
    [
        "CreativeWork",
        "Article",
        "NewsArticle"
    ],
    [
        "CreativeWork",
        "Article",
        "Report"
    ],
    [
        "CreativeWork",
        "Article",
        "ScholarlyArticle",
        "MedicalScholarlyArticle"
    ],
    [
        "CreativeWork",
        "Article",
        "ScholarlyArticle"
    ],
    [
        "CreativeWork",
        "Article",
        "SocialMediaPosting",
        "BlogPosting",
        "LiveBlogPosting"
    ],
    [
        "CreativeWork",
        "Article",
        "SocialMediaPosting",
        "BlogPosting"
    ],
    [
        "CreativeWork",
        "Article",
        "SocialMediaPosting",
        "DiscussionForumPosting"
    ],
    [
        "CreativeWork",
        "Article",
        "SocialMediaPosting"
    ],
    [
        "CreativeWork",
        "Article",
        "TechArticle",
        "APIReference"
    ],
    [
        "CreativeWork",
        "Article",
        "TechArticle"
    ],
    [
        "CreativeWork",
        "Article"
    ],
    [
        "CreativeWork",
        "Atlas"
    ],
    [
        "CreativeWork",
        "Blog"
    ],
    [
        "CreativeWork",
        "Book",
        "Audiobook"
    ],
    [
        "CreativeWork",
        "Book"
    ],
    [
        "CreativeWork",
        "Chapter"
    ],
    [
        "CreativeWork",
        "Clip",
        "MovieClip"
    ],
    [
        "CreativeWork",
        "Clip",
        "RadioClip"
    ],
    [
        "CreativeWork",
        "Clip",
        "TVClip"
    ],
    [
        "CreativeWork",
        "Clip",
        "VideoGameClip"
    ],
    [
        "CreativeWork",
        "Clip"
    ],
    [
        "CreativeWork",
        "Collection"
    ],
    [
        "CreativeWork",
        "ComicStory",
        "ComicCoverArt"
    ],
    [
        "CreativeWork",
        "ComicStory"
    ],
    [
        "CreativeWork",
        "Comment",
        "Answer"
    ],
    [
        "CreativeWork",
        "Comment",
        "Question"
    ],
    [
        "CreativeWork",
        "Comment"
    ],
    [
        "CreativeWork",
        "Conversation"
    ],
    [
        "CreativeWork",
        "Course"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeason",
        "RadioSeason"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeason",
        "TVSeason"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeason"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "BookSeries"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "MovieSeries"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "Periodical",
        "ComicSeries"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "Periodical",
        "Newspaper"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "Periodical"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "RadioSeries"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "TVSeries"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries",
        "VideoGameSeries"
    ],
    [
        "CreativeWork",
        "CreativeWorkSeries"
    ],
    [
        "CreativeWork",
        "DataCatalog"
    ],
    [
        "CreativeWork",
        "Dataset",
        "DataFeed"
    ],
    [
        "CreativeWork",
        "Dataset"
    ],
    [
        "CreativeWork",
        "Diet"
    ],
    [
        "CreativeWork",
        "DigitalDocument",
        "NoteDigitalDocument"
    ],
    [
        "CreativeWork",
        "DigitalDocument",
        "PresentationDigitalDocument"
    ],
    [
        "CreativeWork",
        "DigitalDocument",
        "SpreadsheetDigitalDocument"
    ],
    [
        "CreativeWork",
        "DigitalDocument",
        "TextDigitalDocument"
    ],
    [
        "CreativeWork",
        "DigitalDocument"
    ],
    [
        "CreativeWork",
        "Episode",
        "RadioEpisode"
    ],
    [
        "CreativeWork",
        "Episode",
        "TVEpisode"
    ],
    [
        "CreativeWork",
        "Episode"
    ],
    [
        "CreativeWork",
        "ExercisePlan"
    ],
    [
        "CreativeWork",
        "Game",
        "VideoGame"
    ],
    [
        "CreativeWork",
        "Game"
    ],
    [
        "CreativeWork",
        "HowTo",
        "Recipe"
    ],
    [
        "CreativeWork",
        "HowTo"
    ],
    [
        "CreativeWork",
        "HowToDirection"
    ],
    [
        "CreativeWork",
        "HowToSection"
    ],
    [
        "CreativeWork",
        "HowToStep"
    ],
    [
        "CreativeWork",
        "HowToTip"
    ],
    [
        "CreativeWork",
        "Map"
    ],
    [
        "CreativeWork",
        "MediaObject",
        "AudioObject",
        "Audiobook"
    ],
    [
        "CreativeWork",
        "MediaObject",
        "AudioObject"
    ],
    [
        "CreativeWork",
        "MediaObject",
        "DataDownload"
    ],
    [
        "CreativeWork",
        "MediaObject",
        "ImageObject",
        "Barcode"
    ],
    [
        "CreativeWork",
        "MediaObject",
        "ImageObject"
    ],
    [
        "CreativeWork",
        "MediaObject",
        "MusicVideoObject"
    ],
    [
        "CreativeWork",
        "MediaObject",
        "VideoObject"
    ],
    [
        "CreativeWork",
        "MediaObject"
    ],
    [
        "CreativeWork",
        "Menu"
    ],
    [
        "CreativeWork",
        "MenuSection"
    ],
    [
        "CreativeWork",
        "Message",
        "EmailMessage"
    ],
    [
        "CreativeWork",
        "Message"
    ],
    [
        "CreativeWork",
        "Movie"
    ],
    [
        "CreativeWork",
        "MusicComposition"
    ],
    [
        "CreativeWork",
        "MusicPlaylist",
        "MusicAlbum"
    ],
    [
        "CreativeWork",
        "MusicPlaylist",
        "MusicRelease"
    ],
    [
        "CreativeWork",
        "MusicPlaylist"
    ],
    [
        "CreativeWork",
        "MusicRecording"
    ],
    [
        "CreativeWork",
        "Painting"
    ],
    [
        "CreativeWork",
        "Photograph"
    ],
    [
        "CreativeWork",
        "PublicationIssue",
        "ComicIssue"
    ],
    [
        "CreativeWork",
        "PublicationIssue"
    ],
    [
        "CreativeWork",
        "PublicationVolume"
    ],
    [
        "CreativeWork",
        "Review",
        "ClaimReview"
    ],
    [
        "CreativeWork",
        "Review"
    ],
    [
        "CreativeWork",
        "Sculpture"
    ],
    [
        "CreativeWork",
        "SoftwareApplication",
        "MobileApplication"
    ],
    [
        "CreativeWork",
        "SoftwareApplication",
        "VideoGame"
    ],
    [
        "CreativeWork",
        "SoftwareApplication",
        "WebApplication"
    ],
    [
        "CreativeWork",
        "SoftwareApplication"
    ],
    [
        "CreativeWork",
        "SoftwareSourceCode"
    ],
    [
        "CreativeWork",
        "TVSeason"
    ],
    [
        "CreativeWork",
        "TVSeries"
    ],
    [
        "CreativeWork",
        "Thesis"
    ],
    [
        "CreativeWork",
        "VisualArtwork",
        "CoverArt",
        "ComicCoverArt"
    ],
    [
        "CreativeWork",
        "VisualArtwork",
        "CoverArt"
    ],
    [
        "CreativeWork",
        "VisualArtwork"
    ],
    [
        "CreativeWork",
        "WebPage",
        "AboutPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "CheckoutPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "CollectionPage",
        "MediaGallery",
        "ImageGallery"
    ],
    [
        "CreativeWork",
        "WebPage",
        "CollectionPage",
        "MediaGallery",
        "VideoGallery"
    ],
    [
        "CreativeWork",
        "WebPage",
        "CollectionPage",
        "MediaGallery"
    ],
    [
        "CreativeWork",
        "WebPage",
        "CollectionPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "ContactPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "FAQPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "ItemPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "MedicalWebPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "ProfilePage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "QAPage"
    ],
    [
        "CreativeWork",
        "WebPage",
        "SearchResultsPage"
    ],
    [
        "CreativeWork",
        "WebPage"
    ],
    [
        "CreativeWork",
        "WebPageElement",
        "SiteNavigationElement"
    ],
    [
        "CreativeWork",
        "WebPageElement",
        "Table"
    ],
    [
        "CreativeWork",
        "WebPageElement",
        "WPAdBlock"
    ],
    [
        "CreativeWork",
        "WebPageElement",
        "WPFooter"
    ],
    [
        "CreativeWork",
        "WebPageElement",
        "WPHeader"
    ],
    [
        "CreativeWork",
        "WebPageElement",
        "WPSideBar"
    ],
    [
        "CreativeWork",
        "WebPageElement"
    ],
    [
        "CreativeWork",
        "WebSite"
    ],
    [
        "CreativeWork"
    ],
    [
        "Event",
        "BusinessEvent"
    ],
    [
        "Event",
        "ChildrensEvent"
    ],
    [
        "Event",
        "ComedyEvent"
    ],
    [
        "Event",
        "CourseInstance"
    ],
    [
        "Event",
        "DanceEvent"
    ],
    [
        "Event",
        "DeliveryEvent"
    ],
    [
        "Event",
        "EducationEvent"
    ],
    [
        "Event",
        "ExhibitionEvent"
    ],
    [
        "Event",
        "Festival"
    ],
    [
        "Event",
        "FoodEvent"
    ],
    [
        "Event",
        "LiteraryEvent"
    ],
    [
        "Event",
        "MusicEvent"
    ],
    [
        "Event",
        "PublicationEvent",
        "BroadcastEvent"
    ],
    [
        "Event",
        "PublicationEvent",
        "OnDemandEvent"
    ],
    [
        "Event",
        "PublicationEvent"
    ],
    [
        "Event",
        "SaleEvent"
    ],
    [
        "Event",
        "ScreeningEvent"
    ],
    [
        "Event",
        "SocialEvent"
    ],
    [
        "Event",
        "SportsEvent"
    ],
    [
        "Event",
        "TheaterEvent"
    ],
    [
        "Event",
        "VisualArtsEvent"
    ],
    [
        "Event"
    ],
    [
        "Intangible",
        "ActionAccessSpecification"
    ],
    [
        "Intangible",
        "AlignmentObject"
    ],
    [
        "Intangible",
        "Audience",
        "BusinessAudience"
    ],
    [
        "Intangible",
        "Audience",
        "EducationalAudience"
    ],
    [
        "Intangible",
        "Audience",
        "MedicalAudience",
        "Patient"
    ],
    [
        "Intangible",
        "Audience",
        "MedicalAudience"
    ],
    [
        "Intangible",
        "Audience",
        "PeopleAudience",
        "MedicalAudience",
        "Patient"
    ],
    [
        "Intangible",
        "Audience",
        "PeopleAudience",
        "MedicalAudience"
    ],
    [
        "Intangible",
        "Audience",
        "PeopleAudience",
        "ParentAudience"
    ],
    [
        "Intangible",
        "Audience",
        "PeopleAudience"
    ],
    [
        "Intangible",
        "Audience",
        "Researcher"
    ],
    [
        "Intangible",
        "Audience"
    ],
    [
        "Intangible",
        "BedDetails"
    ],
    [
        "Intangible",
        "Brand"
    ],
    [
        "Intangible",
        "BroadcastChannel",
        "RadioChannel",
        "AMRadioChannel"
    ],
    [
        "Intangible",
        "BroadcastChannel",
        "RadioChannel",
        "FMRadioChannel"
    ],
    [
        "Intangible",
        "BroadcastChannel",
        "RadioChannel"
    ],
    [
        "Intangible",
        "BroadcastChannel",
        "TelevisionChannel"
    ],
    [
        "Intangible",
        "BroadcastChannel"
    ],
    [
        "Intangible",
        "BroadcastFrequencySpecification"
    ],
    [
        "Intangible",
        "ComputerLanguage"
    ],
    [
        "Intangible",
        "DataFeedItem"
    ],
    [
        "Intangible",
        "Demand"
    ],
    [
        "Intangible",
        "DigitalDocumentPermission"
    ],
    [
        "Intangible",
        "EntryPoint"
    ],
    [
        "Intangible",
        "Enumeration"
    ],
    [
        "Intangible",
        "GameServer"
    ],
    [
        "Intangible",
        "Invoice"
    ],
    [
        "Intangible",
        "ItemList",
        "BreadcrumbList"
    ],
    [
        "Intangible",
        "ItemList",
        "HowToSection"
    ],
    [
        "Intangible",
        "ItemList",
        "HowToStep"
    ],
    [
        "Intangible",
        "ItemList",
        "OfferCatalog"
    ],
    [
        "Intangible",
        "ItemList"
    ],
    [
        "Intangible",
        "JobPosting"
    ],
    [
        "Intangible",
        "Language"
    ],
    [
        "Intangible",
        "ListItem",
        "HowToDirection"
    ],
    [
        "Intangible",
        "ListItem",
        "HowToItem",
        "HowToSupply"
    ],
    [
        "Intangible",
        "ListItem",
        "HowToItem",
        "HowToTool"
    ],
    [
        "Intangible",
        "ListItem",
        "HowToItem"
    ],
    [
        "Intangible",
        "ListItem",
        "HowToSection"
    ],
    [
        "Intangible",
        "ListItem",
        "HowToStep"
    ],
    [
        "Intangible",
        "ListItem",
        "HowToTip"
    ],
    [
        "Intangible",
        "ListItem"
    ],
    [
        "Intangible",
        "MediaSubscription"
    ],
    [
        "Intangible",
        "MenuItem"
    ],
    [
        "Intangible",
        "Occupation"
    ],
    [
        "Intangible",
        "Offer",
        "AggregateOffer"
    ],
    [
        "Intangible",
        "Offer"
    ],
    [
        "Intangible",
        "Order"
    ],
    [
        "Intangible",
        "OrderItem"
    ],
    [
        "Intangible",
        "ParcelDelivery"
    ],
    [
        "Intangible",
        "Permit",
        "GovernmentPermit"
    ],
    [
        "Intangible",
        "Permit"
    ],
    [
        "Intangible",
        "ProgramMembership"
    ],
    [
        "Intangible",
        "PropertyValueSpecification"
    ],
    [
        "Intangible",
        "Quantity",
        "Distance"
    ],
    [
        "Intangible",
        "Quantity",
        "Duration"
    ],
    [
        "Intangible",
        "Quantity",
        "Energy"
    ],
    [
        "Intangible",
        "Quantity",
        "Mass"
    ],
    [
        "Intangible",
        "Quantity"
    ],
    [
        "Intangible",
        "Rating",
        "AggregateRating",
        "EmployerAggregateRating"
    ],
    [
        "Intangible",
        "Rating",
        "AggregateRating"
    ],
    [
        "Intangible",
        "Rating",
        "EndorsementRating"
    ],
    [
        "Intangible",
        "Rating"
    ],
    [
        "Intangible",
        "Reservation",
        "BusReservation"
    ],
    [
        "Intangible",
        "Reservation",
        "EventReservation"
    ],
    [
        "Intangible",
        "Reservation",
        "FlightReservation"
    ],
    [
        "Intangible",
        "Reservation",
        "FoodEstablishmentReservation"
    ],
    [
        "Intangible",
        "Reservation",
        "LodgingReservation"
    ],
    [
        "Intangible",
        "Reservation",
        "RentalCarReservation"
    ],
    [
        "Intangible",
        "Reservation",
        "ReservationPackage"
    ],
    [
        "Intangible",
        "Reservation",
        "TaxiReservation"
    ],
    [
        "Intangible",
        "Reservation",
        "TrainReservation"
    ],
    [
        "Intangible",
        "Reservation"
    ],
    [
        "Intangible",
        "Role",
        "OrganizationRole",
        "EmployeeRole"
    ],
    [
        "Intangible",
        "Role",
        "OrganizationRole"
    ],
    [
        "Intangible",
        "Role",
        "PerformanceRole"
    ],
    [
        "Intangible",
        "Role"
    ],
    [
        "Intangible",
        "Seat"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "BookSeries"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "MovieSeries"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "Periodical",
        "ComicSeries"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "Periodical",
        "Newspaper"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "Periodical"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "RadioSeries"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "TVSeries"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries",
        "VideoGameSeries"
    ],
    [
        "Intangible",
        "Series",
        "CreativeWorkSeries"
    ],
    [
        "Intangible",
        "Series"
    ],
    [
        "Intangible",
        "Service",
        "BroadcastService"
    ],
    [
        "Intangible",
        "Service",
        "CableOrSatelliteService"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct",
        "BankAccount",
        "DepositAccount"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct",
        "BankAccount"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct",
        "CurrencyConversionService"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct",
        "InvestmentOrDeposit",
        "DepositAccount"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct",
        "InvestmentOrDeposit"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct",
        "LoanOrCredit"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct",
        "PaymentService"
    ],
    [
        "Intangible",
        "Service",
        "FinancialProduct"
    ],
    [
        "Intangible",
        "Service",
        "FoodService"
    ],
    [
        "Intangible",
        "Service",
        "GovernmentService"
    ],
    [
        "Intangible",
        "Service",
        "TaxiService"
    ],
    [
        "Intangible",
        "Service"
    ],
    [
        "Intangible",
        "ServiceChannel"
    ],
    [
        "Intangible",
        "SpeakableSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "ContactPoint",
        "PostalAddress"
    ],
    [
        "Intangible",
        "StructuredValue",
        "ContactPoint"
    ],
    [
        "Intangible",
        "StructuredValue",
        "EngineSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "GeoCoordinates"
    ],
    [
        "Intangible",
        "StructuredValue",
        "GeoShape",
        "GeoCircle"
    ],
    [
        "Intangible",
        "StructuredValue",
        "GeoShape"
    ],
    [
        "Intangible",
        "StructuredValue",
        "InteractionCounter"
    ],
    [
        "Intangible",
        "StructuredValue",
        "MonetaryAmount"
    ],
    [
        "Intangible",
        "StructuredValue",
        "NutritionInformation"
    ],
    [
        "Intangible",
        "StructuredValue",
        "OpeningHoursSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "OwnershipInfo"
    ],
    [
        "Intangible",
        "StructuredValue",
        "PriceSpecification",
        "CompoundPriceSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "PriceSpecification",
        "DeliveryChargeSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "PriceSpecification",
        "PaymentChargeSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "PriceSpecification",
        "UnitPriceSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "PriceSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "PropertyValue",
        "LocationFeatureSpecification"
    ],
    [
        "Intangible",
        "StructuredValue",
        "PropertyValue"
    ],
    [
        "Intangible",
        "StructuredValue",
        "QuantitativeValue"
    ],
    [
        "Intangible",
        "StructuredValue",
        "QuantitativeValueDistribution",
        "MonetaryAmountDistribution"
    ],
    [
        "Intangible",
        "StructuredValue",
        "QuantitativeValueDistribution"
    ],
    [
        "Intangible",
        "StructuredValue",
        "TypeAndQuantityNode"
    ],
    [
        "Intangible",
        "StructuredValue",
        "WarrantyPromise"
    ],
    [
        "Intangible",
        "StructuredValue"
    ],
    [
        "Intangible",
        "Ticket"
    ],
    [
        "Intangible",
        "Trip",
        "BusTrip"
    ],
    [
        "Intangible",
        "Trip",
        "Flight"
    ],
    [
        "Intangible",
        "Trip",
        "TrainTrip"
    ],
    [
        "Intangible",
        "Trip"
    ],
    [
        "Intangible"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Bone"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "BrainStructure"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Joint"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Ligament"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Muscle"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Nerve"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Vessel",
        "Artery"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Vessel",
        "LymphaticVessel"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Vessel",
        "Vein"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure",
        "Vessel"
    ],
    [
        "MedicalEntity",
        "AnatomicalStructure"
    ],
    [
        "MedicalEntity",
        "AnatomicalSystem"
    ],
    [
        "MedicalEntity",
        "DrugClass"
    ],
    [
        "MedicalEntity",
        "DrugCost"
    ],
    [
        "MedicalEntity",
        "LifestyleModification",
        "Diet"
    ],
    [
        "MedicalEntity",
        "LifestyleModification",
        "PhysicalActivity",
        "ExercisePlan"
    ],
    [
        "MedicalEntity",
        "LifestyleModification",
        "PhysicalActivity"
    ],
    [
        "MedicalEntity",
        "LifestyleModification"
    ],
    [
        "MedicalEntity",
        "MedicalCause"
    ],
    [
        "MedicalEntity",
        "MedicalCondition",
        "InfectiousDisease"
    ],
    [
        "MedicalEntity",
        "MedicalCondition",
        "MedicalSignOrSymptom",
        "MedicalSign",
        "VitalSign"
    ],
    [
        "MedicalEntity",
        "MedicalCondition",
        "MedicalSignOrSymptom",
        "MedicalSign"
    ],
    [
        "MedicalEntity",
        "MedicalCondition",
        "MedicalSignOrSymptom",
        "MedicalSymptom"
    ],
    [
        "MedicalEntity",
        "MedicalCondition",
        "MedicalSignOrSymptom"
    ],
    [
        "MedicalEntity",
        "MedicalCondition"
    ],
    [
        "MedicalEntity",
        "MedicalContraindication"
    ],
    [
        "MedicalEntity",
        "MedicalDevice"
    ],
    [
        "MedicalEntity",
        "MedicalGuideline",
        "MedicalGuidelineContraindication"
    ],
    [
        "MedicalEntity",
        "MedicalGuideline",
        "MedicalGuidelineRecommendation"
    ],
    [
        "MedicalEntity",
        "MedicalGuideline"
    ],
    [
        "MedicalEntity",
        "MedicalIndication",
        "ApprovedIndication"
    ],
    [
        "MedicalEntity",
        "MedicalIndication",
        "PreventionIndication"
    ],
    [
        "MedicalEntity",
        "MedicalIndication",
        "TreatmentIndication"
    ],
    [
        "MedicalEntity",
        "MedicalIndication"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "DDxElement"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "DoseSchedule",
        "MaximumDoseSchedule"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "DoseSchedule",
        "RecommendedDoseSchedule"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "DoseSchedule",
        "ReportedDoseSchedule"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "DoseSchedule"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "DrugLegalStatus"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "DrugStrength"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "MedicalCode"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible",
        "MedicalConditionStage"
    ],
    [
        "MedicalEntity",
        "MedicalIntangible"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "DiagnosticProcedure"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "PalliativeProcedure"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "SurgicalProcedure"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "TherapeuticProcedure",
        "MedicalTherapy",
        "OccupationalTherapy"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "TherapeuticProcedure",
        "MedicalTherapy",
        "PalliativeProcedure"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "TherapeuticProcedure",
        "MedicalTherapy",
        "PhysicalTherapy"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "TherapeuticProcedure",
        "MedicalTherapy",
        "RadiationTherapy"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "TherapeuticProcedure",
        "MedicalTherapy"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "TherapeuticProcedure",
        "PsychologicalTreatment"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure",
        "TherapeuticProcedure"
    ],
    [
        "MedicalEntity",
        "MedicalProcedure"
    ],
    [
        "MedicalEntity",
        "MedicalRiskEstimator",
        "MedicalRiskCalculator"
    ],
    [
        "MedicalEntity",
        "MedicalRiskEstimator",
        "MedicalRiskScore"
    ],
    [
        "MedicalEntity",
        "MedicalRiskEstimator"
    ],
    [
        "MedicalEntity",
        "MedicalRiskFactor"
    ],
    [
        "MedicalEntity",
        "MedicalStudy",
        "MedicalObservationalStudy"
    ],
    [
        "MedicalEntity",
        "MedicalStudy",
        "MedicalTrial"
    ],
    [
        "MedicalEntity",
        "MedicalStudy"
    ],
    [
        "MedicalEntity",
        "MedicalTest",
        "BloodTest"
    ],
    [
        "MedicalEntity",
        "MedicalTest",
        "ImagingTest"
    ],
    [
        "MedicalEntity",
        "MedicalTest",
        "MedicalTestPanel"
    ],
    [
        "MedicalEntity",
        "MedicalTest",
        "PathologyTest"
    ],
    [
        "MedicalEntity",
        "MedicalTest"
    ],
    [
        "MedicalEntity",
        "Substance",
        "DietarySupplement"
    ],
    [
        "MedicalEntity",
        "Substance",
        "Drug"
    ],
    [
        "MedicalEntity",
        "Substance"
    ],
    [
        "MedicalEntity",
        "SuperficialAnatomy"
    ],
    [
        "MedicalEntity"
    ],
    [
        "Organization",
        "Airline"
    ],
    [
        "Organization",
        "Corporation"
    ],
    [
        "Organization",
        "EducationalOrganization",
        "CollegeOrUniversity"
    ],
    [
        "Organization",
        "EducationalOrganization",
        "ElementarySchool"
    ],
    [
        "Organization",
        "EducationalOrganization",
        "HighSchool"
    ],
    [
        "Organization",
        "EducationalOrganization",
        "MiddleSchool"
    ],
    [
        "Organization",
        "EducationalOrganization",
        "Preschool"
    ],
    [
        "Organization",
        "EducationalOrganization",
        "School"
    ],
    [
        "Organization",
        "EducationalOrganization"
    ],
    [
        "Organization",
        "GovernmentOrganization"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AnimalShelter"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoBodyShop"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoDealer"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoPartsStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoRental"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoRepair"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoWash"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "GasStation"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "MotorcycleDealer"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness",
        "MotorcycleRepair"
    ],
    [
        "Organization",
        "LocalBusiness",
        "AutomotiveBusiness"
    ],
    [
        "Organization",
        "LocalBusiness",
        "ChildCare"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Dentist"
    ],
    [
        "Organization",
        "LocalBusiness",
        "DryCleaningOrLaundry"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EmergencyService",
        "FireStation"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EmergencyService",
        "Hospital"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EmergencyService",
        "PoliceStation"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EmergencyService"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EmploymentAgency"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness",
        "AdultEntertainment"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness",
        "AmusementPark"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness",
        "ArtGallery"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness",
        "Casino"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness",
        "ComedyClub"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness",
        "MovieTheater"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness",
        "NightClub"
    ],
    [
        "Organization",
        "LocalBusiness",
        "EntertainmentBusiness"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FinancialService",
        "AccountingService"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FinancialService",
        "AutomatedTeller"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FinancialService",
        "BankOrCreditUnion"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FinancialService",
        "InsuranceAgency"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FinancialService"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "Bakery"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "BarOrPub"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "Brewery"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "CafeOrCoffeeShop"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "Distillery"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "FastFoodRestaurant"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "IceCreamShop"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "Restaurant"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment",
        "Winery"
    ],
    [
        "Organization",
        "LocalBusiness",
        "FoodEstablishment"
    ],
    [
        "Organization",
        "LocalBusiness",
        "GovernmentOffice",
        "PostOffice"
    ],
    [
        "Organization",
        "LocalBusiness",
        "GovernmentOffice"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "BeautySalon"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "DaySpa"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "HairSalon"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "HealthClub"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "NailSalon"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "TattooParlor"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HealthAndBeautyBusiness"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "Electrician"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "GeneralContractor"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "HVACBusiness"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "HousePainter"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "Locksmith"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "MovingCompany"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "Plumber"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "RoofingContractor"
    ],
    [
        "Organization",
        "LocalBusiness",
        "HomeAndConstructionBusiness"
    ],
    [
        "Organization",
        "LocalBusiness",
        "InternetCafe"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LegalService",
        "Attorney"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LegalService",
        "Notary"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LegalService"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Library"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness",
        "BedAndBreakfast"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness",
        "Campground"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness",
        "Hostel"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness",
        "Hotel"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness",
        "Motel"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness",
        "Resort",
        "SkiResort"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness",
        "Resort"
    ],
    [
        "Organization",
        "LocalBusiness",
        "LodgingBusiness"
    ],
    [
        "Organization",
        "LocalBusiness",
        "MedicalBusiness",
        "Dentist"
    ],
    [
        "Organization",
        "LocalBusiness",
        "MedicalBusiness",
        "MedicalClinic"
    ],
    [
        "Organization",
        "LocalBusiness",
        "MedicalBusiness",
        "Optician"
    ],
    [
        "Organization",
        "LocalBusiness",
        "MedicalBusiness",
        "Pharmacy"
    ],
    [
        "Organization",
        "LocalBusiness",
        "MedicalBusiness",
        "Physician"
    ],
    [
        "Organization",
        "LocalBusiness",
        "MedicalBusiness"
    ],
    [
        "Organization",
        "LocalBusiness",
        "ProfessionalService"
    ],
    [
        "Organization",
        "LocalBusiness",
        "RadioStation"
    ],
    [
        "Organization",
        "LocalBusiness",
        "RealEstateAgent"
    ],
    [
        "Organization",
        "LocalBusiness",
        "RecyclingCenter"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SelfStorage"
    ],
    [
        "Organization",
        "LocalBusiness",
        "ShoppingCenter"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "BowlingAlley"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "ExerciseGym"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "GolfCourse"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "HealthClub"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "PublicSwimmingPool"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "SkiResort"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "SportsClub"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "StadiumOrArena"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation",
        "TennisComplex"
    ],
    [
        "Organization",
        "LocalBusiness",
        "SportsActivityLocation"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "AutoPartsStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "BikeStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "BookStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "ClothingStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "ComputerStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "ConvenienceStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "DepartmentStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "ElectronicsStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "Florist"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "FurnitureStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "GardenStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "GroceryStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "HardwareStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "HobbyShop"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "HomeGoodsStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "JewelryStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "LiquorStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "MensClothingStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "MobilePhoneStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "MovieRentalStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "MusicStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "OfficeEquipmentStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "OutletStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "PawnShop"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "PetStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "ShoeStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "SportingGoodsStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "TireShop"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "ToyStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store",
        "WholesaleStore"
    ],
    [
        "Organization",
        "LocalBusiness",
        "Store"
    ],
    [
        "Organization",
        "LocalBusiness",
        "TelevisionStation"
    ],
    [
        "Organization",
        "LocalBusiness",
        "TouristInformationCenter"
    ],
    [
        "Organization",
        "LocalBusiness",
        "TravelAgency"
    ],
    [
        "Organization",
        "LocalBusiness"
    ],
    [
        "Organization",
        "MedicalOrganization",
        "Dentist"
    ],
    [
        "Organization",
        "MedicalOrganization",
        "DiagnosticLab"
    ],
    [
        "Organization",
        "MedicalOrganization",
        "Hospital"
    ],
    [
        "Organization",
        "MedicalOrganization",
        "MedicalClinic"
    ],
    [
        "Organization",
        "MedicalOrganization",
        "Pharmacy"
    ],
    [
        "Organization",
        "MedicalOrganization",
        "Physician"
    ],
    [
        "Organization",
        "MedicalOrganization",
        "VeterinaryCare"
    ],
    [
        "Organization",
        "MedicalOrganization"
    ],
    [
        "Organization",
        "NGO"
    ],
    [
        "Organization",
        "PerformingGroup",
        "DanceGroup"
    ],
    [
        "Organization",
        "PerformingGroup",
        "MusicGroup"
    ],
    [
        "Organization",
        "PerformingGroup",
        "TheaterGroup"
    ],
    [
        "Organization",
        "PerformingGroup"
    ],
    [
        "Organization",
        "SportsOrganization",
        "SportsTeam"
    ],
    [
        "Organization",
        "SportsOrganization"
    ],
    [
        "Organization",
        "WorkersUnion"
    ],
    [
        "Organization"
    ],
    [
        "Person",
        "Patient"
    ],
    [
        "Person"
    ],
    [
        "Place",
        "Accommodation",
        "Apartment"
    ],
    [
        "Place",
        "Accommodation",
        "CampingPitch"
    ],
    [
        "Place",
        "Accommodation",
        "House",
        "SingleFamilyResidence"
    ],
    [
        "Place",
        "Accommodation",
        "House"
    ],
    [
        "Place",
        "Accommodation",
        "Room",
        "HotelRoom"
    ],
    [
        "Place",
        "Accommodation",
        "Room",
        "MeetingRoom"
    ],
    [
        "Place",
        "Accommodation",
        "Room"
    ],
    [
        "Place",
        "Accommodation",
        "Suite"
    ],
    [
        "Place",
        "Accommodation"
    ],
    [
        "Place",
        "AdministrativeArea",
        "City"
    ],
    [
        "Place",
        "AdministrativeArea",
        "Country"
    ],
    [
        "Place",
        "AdministrativeArea",
        "State"
    ],
    [
        "Place",
        "AdministrativeArea"
    ],
    [
        "Place",
        "CivicStructure",
        "Airport"
    ],
    [
        "Place",
        "CivicStructure",
        "Aquarium"
    ],
    [
        "Place",
        "CivicStructure",
        "Beach"
    ],
    [
        "Place",
        "CivicStructure",
        "Bridge"
    ],
    [
        "Place",
        "CivicStructure",
        "BusStation"
    ],
    [
        "Place",
        "CivicStructure",
        "BusStop"
    ],
    [
        "Place",
        "CivicStructure",
        "Campground"
    ],
    [
        "Place",
        "CivicStructure",
        "Cemetery"
    ],
    [
        "Place",
        "CivicStructure",
        "Crematorium"
    ],
    [
        "Place",
        "CivicStructure",
        "EducationalOrganization",
        "CollegeOrUniversity"
    ],
    [
        "Place",
        "CivicStructure",
        "EducationalOrganization",
        "ElementarySchool"
    ],
    [
        "Place",
        "CivicStructure",
        "EducationalOrganization",
        "HighSchool"
    ],
    [
        "Place",
        "CivicStructure",
        "EducationalOrganization",
        "MiddleSchool"
    ],
    [
        "Place",
        "CivicStructure",
        "EducationalOrganization",
        "Preschool"
    ],
    [
        "Place",
        "CivicStructure",
        "EducationalOrganization",
        "School"
    ],
    [
        "Place",
        "CivicStructure",
        "EducationalOrganization"
    ],
    [
        "Place",
        "CivicStructure",
        "EventVenue"
    ],
    [
        "Place",
        "CivicStructure",
        "FireStation"
    ],
    [
        "Place",
        "CivicStructure",
        "GovernmentBuilding",
        "CityHall"
    ],
    [
        "Place",
        "CivicStructure",
        "GovernmentBuilding",
        "Courthouse"
    ],
    [
        "Place",
        "CivicStructure",
        "GovernmentBuilding",
        "DefenceEstablishment"
    ],
    [
        "Place",
        "CivicStructure",
        "GovernmentBuilding",
        "Embassy"
    ],
    [
        "Place",
        "CivicStructure",
        "GovernmentBuilding",
        "LegislativeBuilding"
    ],
    [
        "Place",
        "CivicStructure",
        "GovernmentBuilding"
    ],
    [
        "Place",
        "CivicStructure",
        "Hospital"
    ],
    [
        "Place",
        "CivicStructure",
        "MovieTheater"
    ],
    [
        "Place",
        "CivicStructure",
        "Museum"
    ],
    [
        "Place",
        "CivicStructure",
        "MusicVenue"
    ],
    [
        "Place",
        "CivicStructure",
        "Park"
    ],
    [
        "Place",
        "CivicStructure",
        "ParkingFacility"
    ],
    [
        "Place",
        "CivicStructure",
        "PerformingArtsTheater"
    ],
    [
        "Place",
        "CivicStructure",
        "PlaceOfWorship",
        "BuddhistTemple"
    ],
    [
        "Place",
        "CivicStructure",
        "PlaceOfWorship",
        "Church",
        "CatholicChurch"
    ],
    [
        "Place",
        "CivicStructure",
        "PlaceOfWorship",
        "Church"
    ],
    [
        "Place",
        "CivicStructure",
        "PlaceOfWorship",
        "HinduTemple"
    ],
    [
        "Place",
        "CivicStructure",
        "PlaceOfWorship",
        "Mosque"
    ],
    [
        "Place",
        "CivicStructure",
        "PlaceOfWorship",
        "Synagogue"
    ],
    [
        "Place",
        "CivicStructure",
        "PlaceOfWorship"
    ],
    [
        "Place",
        "CivicStructure",
        "Playground"
    ],
    [
        "Place",
        "CivicStructure",
        "PoliceStation"
    ],
    [
        "Place",
        "CivicStructure",
        "RVPark"
    ],
    [
        "Place",
        "CivicStructure",
        "StadiumOrArena"
    ],
    [
        "Place",
        "CivicStructure",
        "SubwayStation"
    ],
    [
        "Place",
        "CivicStructure",
        "TaxiStand"
    ],
    [
        "Place",
        "CivicStructure",
        "TrainStation"
    ],
    [
        "Place",
        "CivicStructure",
        "Zoo"
    ],
    [
        "Place",
        "CivicStructure"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "Canal"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "LakeBodyOfWater"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "OceanBodyOfWater"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "Pond"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "Reservoir"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "RiverBodyOfWater"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "SeaBodyOfWater"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater",
        "Waterfall"
    ],
    [
        "Place",
        "Landform",
        "BodyOfWater"
    ],
    [
        "Place",
        "Landform",
        "Continent"
    ],
    [
        "Place",
        "Landform",
        "Mountain"
    ],
    [
        "Place",
        "Landform",
        "Volcano"
    ],
    [
        "Place",
        "Landform"
    ],
    [
        "Place",
        "LandmarksOrHistoricalBuildings"
    ],
    [
        "Place",
        "LocalBusiness",
        "AnimalShelter"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoBodyShop"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoDealer"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoPartsStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoRental"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoRepair"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "AutoWash"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "GasStation"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "MotorcycleDealer"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness",
        "MotorcycleRepair"
    ],
    [
        "Place",
        "LocalBusiness",
        "AutomotiveBusiness"
    ],
    [
        "Place",
        "LocalBusiness",
        "ChildCare"
    ],
    [
        "Place",
        "LocalBusiness",
        "Dentist"
    ],
    [
        "Place",
        "LocalBusiness",
        "DryCleaningOrLaundry"
    ],
    [
        "Place",
        "LocalBusiness",
        "EmergencyService",
        "FireStation"
    ],
    [
        "Place",
        "LocalBusiness",
        "EmergencyService",
        "Hospital"
    ],
    [
        "Place",
        "LocalBusiness",
        "EmergencyService",
        "PoliceStation"
    ],
    [
        "Place",
        "LocalBusiness",
        "EmergencyService"
    ],
    [
        "Place",
        "LocalBusiness",
        "EmploymentAgency"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness",
        "AdultEntertainment"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness",
        "AmusementPark"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness",
        "ArtGallery"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness",
        "Casino"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness",
        "ComedyClub"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness",
        "MovieTheater"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness",
        "NightClub"
    ],
    [
        "Place",
        "LocalBusiness",
        "EntertainmentBusiness"
    ],
    [
        "Place",
        "LocalBusiness",
        "FinancialService",
        "AccountingService"
    ],
    [
        "Place",
        "LocalBusiness",
        "FinancialService",
        "AutomatedTeller"
    ],
    [
        "Place",
        "LocalBusiness",
        "FinancialService",
        "BankOrCreditUnion"
    ],
    [
        "Place",
        "LocalBusiness",
        "FinancialService",
        "InsuranceAgency"
    ],
    [
        "Place",
        "LocalBusiness",
        "FinancialService"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "Bakery"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "BarOrPub"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "Brewery"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "CafeOrCoffeeShop"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "Distillery"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "FastFoodRestaurant"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "IceCreamShop"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "Restaurant"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment",
        "Winery"
    ],
    [
        "Place",
        "LocalBusiness",
        "FoodEstablishment"
    ],
    [
        "Place",
        "LocalBusiness",
        "GovernmentOffice",
        "PostOffice"
    ],
    [
        "Place",
        "LocalBusiness",
        "GovernmentOffice"
    ],
    [
        "Place",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "BeautySalon"
    ],
    [
        "Place",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "DaySpa"
    ],
    [
        "Place",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "HairSalon"
    ],
    [
        "Place",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "HealthClub"
    ],
    [
        "Place",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "NailSalon"
    ],
    [
        "Place",
        "LocalBusiness",
        "HealthAndBeautyBusiness",
        "TattooParlor"
    ],
    [
        "Place",
        "LocalBusiness",
        "HealthAndBeautyBusiness"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "Electrician"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "GeneralContractor"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "HVACBusiness"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "HousePainter"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "Locksmith"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "MovingCompany"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "Plumber"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness",
        "RoofingContractor"
    ],
    [
        "Place",
        "LocalBusiness",
        "HomeAndConstructionBusiness"
    ],
    [
        "Place",
        "LocalBusiness",
        "InternetCafe"
    ],
    [
        "Place",
        "LocalBusiness",
        "LegalService",
        "Attorney"
    ],
    [
        "Place",
        "LocalBusiness",
        "LegalService",
        "Notary"
    ],
    [
        "Place",
        "LocalBusiness",
        "LegalService"
    ],
    [
        "Place",
        "LocalBusiness",
        "Library"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness",
        "BedAndBreakfast"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness",
        "Campground"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness",
        "Hostel"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness",
        "Hotel"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness",
        "Motel"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness",
        "Resort",
        "SkiResort"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness",
        "Resort"
    ],
    [
        "Place",
        "LocalBusiness",
        "LodgingBusiness"
    ],
    [
        "Place",
        "LocalBusiness",
        "MedicalBusiness",
        "Dentist"
    ],
    [
        "Place",
        "LocalBusiness",
        "MedicalBusiness",
        "MedicalClinic"
    ],
    [
        "Place",
        "LocalBusiness",
        "MedicalBusiness",
        "Optician"
    ],
    [
        "Place",
        "LocalBusiness",
        "MedicalBusiness",
        "Pharmacy"
    ],
    [
        "Place",
        "LocalBusiness",
        "MedicalBusiness",
        "Physician"
    ],
    [
        "Place",
        "LocalBusiness",
        "MedicalBusiness"
    ],
    [
        "Place",
        "LocalBusiness",
        "ProfessionalService"
    ],
    [
        "Place",
        "LocalBusiness",
        "RadioStation"
    ],
    [
        "Place",
        "LocalBusiness",
        "RealEstateAgent"
    ],
    [
        "Place",
        "LocalBusiness",
        "RecyclingCenter"
    ],
    [
        "Place",
        "LocalBusiness",
        "SelfStorage"
    ],
    [
        "Place",
        "LocalBusiness",
        "ShoppingCenter"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "BowlingAlley"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "ExerciseGym"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "GolfCourse"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "HealthClub"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "PublicSwimmingPool"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "SkiResort"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "SportsClub"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "StadiumOrArena"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation",
        "TennisComplex"
    ],
    [
        "Place",
        "LocalBusiness",
        "SportsActivityLocation"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "AutoPartsStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "BikeStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "BookStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "ClothingStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "ComputerStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "ConvenienceStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "DepartmentStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "ElectronicsStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "Florist"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "FurnitureStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "GardenStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "GroceryStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "HardwareStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "HobbyShop"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "HomeGoodsStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "JewelryStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "LiquorStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "MensClothingStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "MobilePhoneStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "MovieRentalStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "MusicStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "OfficeEquipmentStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "OutletStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "PawnShop"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "PetStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "ShoeStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "SportingGoodsStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "TireShop"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "ToyStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store",
        "WholesaleStore"
    ],
    [
        "Place",
        "LocalBusiness",
        "Store"
    ],
    [
        "Place",
        "LocalBusiness",
        "TelevisionStation"
    ],
    [
        "Place",
        "LocalBusiness",
        "TouristInformationCenter"
    ],
    [
        "Place",
        "LocalBusiness",
        "TravelAgency"
    ],
    [
        "Place",
        "LocalBusiness"
    ],
    [
        "Place",
        "Residence",
        "ApartmentComplex"
    ],
    [
        "Place",
        "Residence",
        "GatedResidenceCommunity"
    ],
    [
        "Place",
        "Residence"
    ],
    [
        "Place",
        "TouristAttraction"
    ],
    [
        "Place"
    ],
    [
        "Product",
        "IndividualProduct"
    ],
    [
        "Product",
        "ProductModel"
    ],
    [
        "Product",
        "SomeProducts"
    ],
    [
        "Product",
        "Vehicle",
        "BusOrCoach"
    ],
    [
        "Product",
        "Vehicle",
        "Car"
    ],
    [
        "Product",
        "Vehicle",
        "Motorcycle"
    ],
    [
        "Product",
        "Vehicle",
        "MotorizedBicycle"
    ],
    [
        "Product",
        "Vehicle"
    ],
    [
        "Product"
    ]
];
